title: "My Blog"
email: "muina@duck.com"
description: "A simple blog based on Editorial template"
baseurl: "" # root directory
url: "https://hakim.orderio.my.id/12345" # URL GitHub Pages

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

