title: "My Blog"
email: "muina@duck.com"
description: "A simple blog based on Editorial template"
baseurl: "/12345" # root directory
url: "https://hakim.orderio.my.id" # URL GitHub Pages

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

